### ISSUE TITLE
Modify file structure of repo to represent how it should look like if someone were to reproduce your analysis.

### ISSUE THREAD

**Issue by marschmi** [rprops/Mussel_feeding#1]
In the **README.md**, you have directions for creating a file structure.  I suggest modifying the file structure of the repo itself to reflect these directions.  That way, if people would like to reproduce your work, they can `git clone` and then go from there without having to move files around.

**Comment by rprops** [comment]
Unable to make empty directories because these would overwrite my local ones + you can't push empty directories afaik
