### ISSUE TITLE
Add modified parameter/function details to the README.md or elsewhere 

### ISSUE THREAD

**Issue by marschmi** [rprops/Mussel_feeding#2]
In the **README.md**,  you suggest in the notice that if the user would like to directly match the paper that they will have to modify specific functions that are currently set. I think it is best to be upfront and obvious about what has been modified from the real analysis as to not force the user to go searching for the parameters that have been modified.

Therefore, I suggest directly stating in the **README.md** which parameters and functions have been changed to decrease computation time.  That way, the reader knows *exactly* what to change to re-run the exact analysis.  The could also be directed to a specific paragraph of the paper or other file in the repo with directions on how to do this.

**Comment by rprops** [comment]
Will do.
